### ISSUE TITLE
New York State Minimum Wage 2020

### ISSUE THREAD

**Issue by are54** [equitablegrowth/VZ_historicalminwage#2]
Thanks for putting this dataset together. It looks like there may be a data entry issue for the New York State minimum wage in 2020. I believe it should say 12.50 instead of 112.5. See https://www.labor.ny.gov/workerprotection/laborstandards/workprot/minwage.shtm

**Comment by kvaghul** [comment]
Thanks so much for letting us know about the data entry issue! We're making the edit right now. Thanks, again!

**Comment by kvaghul** [comment]
Thanks for your help in fixing this issue. The raw data file has been updated to reflect the correct New York state minimum wage for 2020 (12.50).
